### ISSUE TITLE
How to solove the problem of RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by ywb3884** [tdurieux/anonymous_github#108]
Great appreciation for sharing such amazing work! But when I try to reproduce your result, An error occurred and it's shown "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn". Could you please help me find what I missed out?
Full Stacktrace:
----------------------------------------------------------------------------------------------------------------------------------------------------

>>>[INFO] Epoch: 1/20  Iter: 5908/5909  Total Loss: 8.177  Time: 1.99

>>>[INFO] Epoch: 1/20   Total Training Loss: 8.816  Time/Epoch: 3.24 hrs
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    main()
  File "main.py", line 282, in main
    test_loss = test(test_data)
  File "main.py", line 214, in test
    dispEst = model(imgL, imgR)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_a
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_a
    output.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yangwenbang/workspace/ITSA/models/GwcNet/stackhourglass.py", line 244, in forward
    gradL = torch.autograd.grad(outputs=featL_["gwc_feature"], inputs=imgL_, grad_outputs=torch.ones_like(fcreate_graph=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 226, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

----------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by tdurieux** [comment]
This is only the anonymous github, please contact the author of the paper
