### ISSUE TITLE
Installing an Own Instance of Anonymous GitHub 

### ISSUE THREAD

**Issue by LennartPurucker** [tdurieux/anonymous_github#166]
Heyho,

I can only get the server to run (by starting the containers) when running `tsc` to compile the typescript beforehand.

Otherwise, I am receiving the following error:
```
anonymous_github-anonymous_github-1  | Error: File /app/build/src/processes/removeCache.js does not exist
anonymous_github-anonymous_github-1  |     at new Worker (/app/node_modules/bullmq/src/classes/worker.ts:220:17)
anonymous_github-anonymous_github-1  |     at startWorker (/app/src/queue.ts:39:23)
anonymous_github-anonymous_github-1  |     at /app/src/server.ts:52:14
anonymous_github-anonymous_github-1  |     at Generator.next (<anonymous>)
anonymous_github-anonymous_github-1  |     at /app/src/server.ts:8:71
anonymous_github-anonymous_github-1  |     at new Promise (<anonymous>)
anonymous_github-anonymous_github-1  |     at __awaiter (/app/src/server.ts:4:12)
anonymous_github-anonymous_github-1  |     at start (/app/src/server.ts:39:12)
anonymous_github-anonymous_github-1  |     at Object.<anonymous> (/app/index.ts:7:7)
anonymous_github-anonymous_github-1  |     at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

This is not part of the install documentation in the README. 
Moreover, I do not fully understand why this works for the containers to be honest.

Therefore, I am wondering what I am doing wrong or what I should do instead.

Thanks for any help in advance.

**Comment by tdurieux** [comment]
Hello,

Yes, i should be improving this part.
It is working because I am mounting the working directory inside the container.
